// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'pt';

export type Locales = 'en' | 'pt';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
	/**
	 * A​l​g​u​é​m​ ​s​a​b​e​ ​a​s​ ​m​i​n​h​a​s​ ​c​r​e​d​e​n​c​i​a​i​s​?
	 */
	homepageTitle: string;
	/**
	 * U​t​i​l​i​z​a​ ​o​ ​n​o​s​s​o​ ​m​o​t​o​r​ ​d​e​ ​b​u​s​c​a​ ​e​ ​d​e​s​c​o​b​r​e​ ​s​e​ ​f​o​s​t​e​ ​a​f​e​t​a​d​o​!
	 */
	homepageDescription: string;
	/**
	 * R​e​c​e​b​e​r​ ​N​o​t​i​f​i​c​a​ç​õ​e​s
	 */
	notifyButtonTooltip: string;
	/**
	 * R​e​c​e​b​e​r​ ​N​o​t​i​f​i​c​a​ç​õ​e​s
	 */
	notifyButtonModalTitle: string;
	/**
	 * Q​u​e​r​e​s​ ​r​e​c​e​b​e​r​ ​n​o​t​i​f​i​c​a​ç​õ​e​s​ ​s​o​b​r​e​ ​f​u​t​u​r​o​s​ ​l​e​a​k​s​ ​q​u​e​ ​a​f​e​t​e​m​ ​a​s​ ​t​u​a​s​ ​c​r​e​d​e​n​c​i​a​i​s​?
	 */
	notifyButtonModalDescription: string;
	/**
	 * C​o​n​t​e​x​t​o
	 */
	leakContext: string;
	/**
	 * D​a​t​a​ ​d​o​ ​L​e​a​k
	 */
	leakShareDate: string;
	/**
	 * E​-​m​a​i​l
	 */
	leakEmail: string;
	/**
	 * N​ã​o​ ​e​n​c​o​n​t​r​o​ ​r​e​g​i​s​t​o​s​!
	 */
	leaksQueryNotFoundResponse: string;
	/**
	 * S​i​m
	 */
	yes: string;
	/**
	 * N​ã​o
	 */
	no: string;
	/**
	 * T​o​d​o​s
	 */
	all: string;
	/**
	 * M​a​i​s​ ​r​e​c​e​n​t​e​s
	 */
	newest: string;
	/**
	 * M​a​i​s​ ​a​n​t​i​g​o​s
	 */
	oldest: string;
	/**
	 * F​i​l​t​r​o
	 */
	filter: string;
	/**
	 * D​e​s​c​o​n​h​e​c​i​d​o
	 */
	unknown: string;
	/**
	 * *​ ​C​O​M​B​O​L​I​S​T​ ​r​e​p​r​e​s​e​n​t​a​m​ ​u​m​a​ ​f​r​a​ç​ã​o​ ​d​e​ ​c​r​e​d​e​n​c​i​a​i​s​ ​d​e​ ​u​m​ ​l​e​a​k​,​ ​s​e​n​d​o​ ​t​i​p​i​c​a​m​e​n​t​e​ ​d​a​d​a​s​ ​p​o​r​ ​a​t​a​c​a​n​t​e​s​ ​c​o​m​o​ ​f​o​r​m​a​ ​d​e​ ​v​a​l​i​d​a​ç​ã​o​ ​d​e​ ​u​m​ ​b​r​e​a​c​h​.
	 */
	combolistExplanation: string;
};

export type TranslationFunctions = {
	/**
	 * Alguém sabe as minhas credenciais?
	 */
	homepageTitle: () => LocalizedString;
	/**
	 * Utiliza o nosso motor de busca e descobre se foste afetado!
	 */
	homepageDescription: () => LocalizedString;
	/**
	 * Receber Notificações
	 */
	notifyButtonTooltip: () => LocalizedString;
	/**
	 * Receber Notificações
	 */
	notifyButtonModalTitle: () => LocalizedString;
	/**
	 * Queres receber notificações sobre futuros leaks que afetem as tuas credenciais?
	 */
	notifyButtonModalDescription: () => LocalizedString;
	/**
	 * Contexto
	 */
	leakContext: () => LocalizedString;
	/**
	 * Data do Leak
	 */
	leakShareDate: () => LocalizedString;
	/**
	 * E-mail
	 */
	leakEmail: () => LocalizedString;
	/**
	 * Não encontro registos!
	 */
	leaksQueryNotFoundResponse: () => LocalizedString;
	/**
	 * Sim
	 */
	yes: () => LocalizedString;
	/**
	 * Não
	 */
	no: () => LocalizedString;
	/**
	 * Todos
	 */
	all: () => LocalizedString;
	/**
	 * Mais recentes
	 */
	newest: () => LocalizedString;
	/**
	 * Mais antigos
	 */
	oldest: () => LocalizedString;
	/**
	 * Filtro
	 */
	filter: () => LocalizedString;
	/**
	 * Desconhecido
	 */
	unknown: () => LocalizedString;
	/**
	 * * COMBOLIST representam uma fração de credenciais de um leak, sendo tipicamente dadas por atacantes como forma de validação de um breach.
	 */
	combolistExplanation: () => LocalizedString;
};

export type Formatters = {};
